spring:
  servlet:
    multipart:
      max-file-size: 20MB # 최대 파일 사이즈
      max-request-size: 20MB # 최대 요청 사이즈
  cloud:
    aws:
      credentials:
        access-key: {AWS_ACCESS_KEY_ID} # IAM에서 생성한 access-key
        secret-key: {AWS_SECRET_ACCESS_KEY} # IAM에서 생성한 secret-key
      region:
        static: ap-northeast-2 # 버킷 region
      s3:
        bucket: ai-styling-s3 # 버킷 이름
      stack:
        auto: false