server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://aistyling.cloc8ek6u83h.ap-northeast-2.rds.amazonaws.com:3306/aistyling
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: ai12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace